name: Format Python code

on:
  push:
    branches: [ main, develop, test ] 
    paths:
      - "**.py"
  workflow_dispatch:

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Install Python and Git
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip git
          python3 -m pip install --upgrade pip
      - name: Install Python requirements
        run: |
          python3 -m pip install black "black[jupyter]"

      - name: Apply formatting
        run: |
          python3 -m black .

      - name: Commit changes
        run: |
          CURR_BRANCH=$(git branch --show-current)
          git config --global user.name "Macrosynergy Automations Bot"
          git config --global user.email "automation@macrosynergy.com"
          git add .
          git commit -m "Auto-formatting code"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/macrosynergy/macrosynergy
          git push origin $CURR_BRANCH

