# This is a workflow in for running the package tests for the macrosynergy package when doing a release to PyPI.
# It runs on Ubuntu, Windows and MacOS, for Python 3.8, 3.9, 3.10 and 3.11.

name: Test Python package on Ubuntu

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  run-unit-tests-matrix:
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install .[test]

      - name: Lint with flake8
        run: |
          # Options: exluding docs, scripts and build folders. Also, treating certain errors as warnings.
          flake8 --count --select=E9,F63,F7,F82 --show-source --exclude=./docs/**,./.github/scripts/*,./build/** --statistics
          flake8 --count --exit-zero --max-complexity=10 --max-line-length=127 --exclude=./docs/**,./.github/scripts/*,./build/** --statistics

      - name: Test with pytest
        run: |
          # Options: --ignore=tests/specific.py --ignore-glob=tests/ignore-pattern
          pytest tests/unit/

      - name: Test build settings
        run: |
          pip uninstall -y macrosynergy
          pip install .[all] 
          python -c "import macrosynergy; print(macrosynergy.__version__)"
          
