name: Test Python package on Ubuntu (Python 3.7.9)

on:
  pull_request:
    branches: [test, develop]
  workflow_dispatch:

jobs:
  prepare-matrix:
    runs-on: ubuntu-24.04
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4

      - id: set-matrix
        run: |
          FOLDERS=$(ls -d tests/unit/*/ | sed 's|tests/unit/||' | sed 's|/||' | jq -R -s -c 'split("\n")[:-1]')
          echo "Matrix: $FOLDERS"
          echo "::set-output name=matrix::$FOLDERS"

  run-unit-tests:
    needs: prepare-matrix
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        folder: ${{fromJson(needs.prepare-matrix.outputs.matrix)}}
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: 3.7.9
          activate-environment: py379
      - name: Test conda installation
        shell: bash -l {0}
        run: conda info

      - name: Install dependencies
        shell: bash -l {0}
        run: |
          conda init
          conda activate py379
          uv pip install . --no-deps
          uv pip install -r tests/requirements-py37.txt
          uv pip uninstall macrosynergy
      - name: Check for sys.path.append
        run: |
          bash .github/scripts/check_sys_path.sh
      - name: Check Python installation
        shell: bash -l {0}
        run: |
          python -c "import sys; assert(int(sys.version_info[:3] == (3,7,9)))"

      - name: Lint with flake8
        shell: bash -l {0}
        run: |
          flake8 --count --select=E9,F63,F7,F82 --show-source --exclude=./docs/**,./.github/scripts/*,./build/** --statistics
          flake8 --count --exit-zero --max-complexity=10 --max-line-length=127 --exclude=./docs/**,./.github/scripts/*,./build/** --statistics

      - name: Test with pytest for ${{ matrix.folder }}
        shell: bash -l {0}
        run: |
          python -c "import sys; assert(int(sys.version_info[:3] == (3,7,9)))"
          python -m pytest ./tests/unit/${{ matrix.folder }}

  run-unit-tests-success:
    needs: run-unit-tests
    runs-on: ubuntu-24.04
    steps:
      - name: Notify on Failure
        run: |
          if [ ${{ job.status }} == 'failure' ]; then
            echo "Unit tests failed"
            exit 1
          else
            echo "Unit tests passed"
          fi
