name: Test Python package on Ubuntu (Python 3.7.9)

on:
  pull_request:
    branches: [test, develop, v1.0.0dev]
  workflow_dispatch:

jobs:
  prepare-matrix:
    runs-on: ubuntu-20.04
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4

      - id: set-matrix
        run: |
          FOLDERS=$(ls -d tests/unit/*/ | sed 's|tests/unit/||' | sed 's|/||' | jq -R -s -c 'split("\n")[:-1]')
          echo "Matrix: $FOLDERS"
          echo "::set-output name=matrix::$FOLDERS"

  run-unit-tests:
    needs: prepare-matrix
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        folder: ${{fromJson(needs.prepare-matrix.outputs.matrix)}}
    steps:
      - uses: actions/checkout@v4

      - name: Restore caches - Python 3.7.9
        uses: ./.github/actions/restore-pip-cache
        with:
          python-version: 3.7.9

      - name: Check for sys.path.append
        run: |
          bash .github/scripts/check_sys_path.sh

      - name: Lint with flake8
        run: |
          flake8 --count --select=E9,F63,F7,F82 --show-source --exclude=./docs/**,./.github/scripts/*,./build/** --statistics
          flake8 --count --exit-zero --max-complexity=10 --max-line-length=127 --exclude=./docs/**,./.github/scripts/*,./build/** --statistics

      - name: Test with pytest for ${{ matrix.folder }}
        run: |
          python -m pytest ./tests/unit/${{ matrix.folder }}

  run-unit-tests-success:
    needs: run-unit-tests
    runs-on: ubuntu-latest
    steps:
      - name: Notify on Failure
        run: |
          if [ ${{ job.status }} == 'failure' ]; then
            echo "Unit tests failed"
            exit 1
          else
            echo "Unit tests passed"
          fi

          
