# This workflow will install Python dependencies, run tests and lint with PyPy
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
# and https://doc.pypy.org/en/latest/install.html

name: Test Package with PyPy on Linux

on:
  push:
    branches: [ main, dev, test, prod, develop, release ]
  pull_request:
    branches: [ main, dev, test, prod, develop, release ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['pypy3.7', 'pypy3.9']

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        sudo apt-get update && sudo apt-get -y upgrade
        sudo apt-get -y install libopenblas-dev  pkg-config libopenblas64-dev
        pypy -m ensurepip --upgrade
        pypy -m pip install flake8 pytest sphinx pytest-cov
        if [ -f requirements.txt ]; then pypy -m pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        # Options: --ignore=tests/specific.py --ignore-glob=tests/ignore-pattern
        pypy -m pytest -rEf tests/unit/ --cov macrosynergy -p no:warnings --verbose
